-- Nocturne Cashier - PostgreSQL / Supabase
-- Jalankan di Supabase Dashboard -> SQL Editor.

CREATE TABLE IF NOT EXISTS public.customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    expired_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public."transaction" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id BIGINT NOT NULL REFERENCES public.customer(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    total_price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transaction_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES public."transaction"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES public.item(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    item_count INTEGER NOT NULL CHECK (item_count > 0),
    price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_customer_name ON public.customer(name);
CREATE INDEX IF NOT EXISTS idx_item_name ON public.item(name);
CREATE INDEX IF NOT EXISTS idx_item_expired_date ON public.item(expired_date);
CREATE INDEX IF NOT EXISTS idx_transaction_date ON public."transaction"(date);
CREATE INDEX IF NOT EXISTS idx_transaction_customer ON public."transaction"(customer_id);
CREATE INDEX IF NOT EXISTS idx_transaction_detail_transaction ON public.transaction_detail(transaction_id);
CREATE INDEX IF NOT EXISTS idx_transaction_detail_item ON public.transaction_detail(item_id);

-- Untuk koneksi PHP server-side via PDO, tabel diakses menggunakan role database
-- yang kamu set di environment. Jika memakai koneksi langsung dari server PHP,
-- tidak perlu Supabase anon key.
